### ISSUE TITLE
Proxmox instructions do not work properly

### ISSUE THREAD

**Issue by ryanmuc** [REMnux/docs#13]
The instructions you have for using your virtual appliance with Proxmox do not work correctly.

https://docs.remnux.org/install-distro/get-virtual-appliance

After importing the OVA to Proxmox, a user must manually go into the Options for the VM and modify Boot Order to enable the disk that was imported as an OVA. The imported disk will not automatically be enabled in the Boot Order setting under VM Options.

The VM must also be set to use CPU type qemu32 for the first boot. It will hang while booting Ubuntu when the CPU type is set to qemu32. After it successfully boots and hangs, you then have to Stop the VM, change the CPU type to qemu64, and then Start the VM again. Then it will successfully boot.

The VM will not properly boot if the CPU type is set to qemu64 to begin with.

**Comment by lennyzeltser** [comment]
Thank you very much, @ryanmuc! I adjusted the instructions to reflect your advice.

**Comment by mntyfrsh** [comment]
I did additional testing and there is something wrong with that OVA when imported to Proxmox. After I was able to successfully get the VM to boot in Proxmox, I powered the VM off. Attempting to start the VM again resulted in failure every time. It simply would not boot. The only way I can get the VM to boot is the following:

1. Switch CPU type to 'qemu32'.

2. Boot the VM and let it fail startup. It'll be obvious it's not booting properly because the display will not work properly and you'll never see the desktop.

3. Hard power off the VM.

4. Switch CPU type to 'qemu64'.

5. Boot the VM. It should properly initialize the display and boot to the desktop.

If you really want Proxmox users to use a pre-packaged VM for that platform, I would suggest creating a new image because if I'm a normal user there's no way I'm bothering with the steps I just mentioned to get your appliance to boot properly.

**Comment by lennyzeltser** [comment]
Thank you @mntyfrsh. I adjusted the documentation to capture the steps you outlined above. I'll plan to build a Proxmox appliance to make this easier for people. (Another alternative for Proxmox users is to use the REMnux installer to create their own VM.)

**Comment by justchillbruh** [comment]
I've experienced this issue myself with Proxmox as well, and I think I've figured it out. The issue is the _display_ chosen. SPICE (qxl) requires you to go through that CPU type loop for every boot. If you don't, the screen will either be stuck on _booting hard disk_ or it'll just display a black screen. If you switch the _display_ to something else, like VMware compatible, you'll initially notice some graphical issues, but then it'll work properly. 

If you still want to use SPICE, you'll first need to boot into REMnux, and then modify the `/etc/default/grub` file with `sudo vim /etc/default/grub` (or `sudo nano /etc/default/grub`). You need to find the `GRUB_CMDLINE_LINUX_DEFAULT` line, and then in the quotation marks, add `nomodeset`. My line ended up looking like `GRUB_CMDLINE_LINUX_DEFAULT="quiet splash nomodeset"`.

Run `sudo update-grub`, reboot, and you should be able to use SPICE (qxl) persistently. This has been a common issue with Ubuntu, at least from my understanding. Adding `nomodeset` forces the boot sequence to use generic BIOS video drivers until REMnux actually loads and is ready to take over.

If you still run into any issues, you can also try to install the `spice-vdagent` package using `apt`. I did this when troubleshooting, however I don't think it was needed after trying the `nomodeset` fix.

**Comment by lennyzeltser** [comment]
Thanks for sharing this, @justchillbruh. Is there anything I can do when creating the OVA file to improve Proxmox compatibility?

**Comment by justchillbruh** [comment]
I'd say that, if possible, appending `nomodeset` to the GRUB file, as I mentioned, might be a good idea. Alternatively, the documentation should recommend using a different display, like `VMware Compatible` or `Standard VGA`, for the first boot. *If* they want to use SPICE, they might need to apply the GRUB fix before they can reliably use it.

I actually documented the installation and troubleshooting processes for the display drivers on my blog: https://chillbruh.rocks/posts/proxmox-remnux-install/.

I covered VM creation, importing the VM disk file, and the troubleshooting process I went through for SPICE with the same solution I mentioned above. Hopefully, that provides some context on my experience with the installation process and informs you a bit better when updating the OVA file or documentation.

Thanks for looking into this and for your work with REMnux!

**Comment by lennyzeltser** [comment]
Thanks again for your detailed analysis and the blog post, @justchillbruh! I've updated the documentation and the REMnux installation process (now based on Ubuntu 24.04 Noble, BTW) based on your findings.

  The `remnux install` command now automatically:
  - Detects when running on KVM/QEMU/Proxmox
  - Installs `qemu-guest-agent` and `spice-vdagent`
  - Applies the `nomodeset` fix to GRUB

  The [updated Proxmox instructions](https://docs.remnux.org/install-distro/get-virtual-appliance#proxmox) now recommend:
  1. Using Standard VGA for the first boot
  2. Running `remnux install` to configure guest tools and display fixes
  3. Then switching to SPICE for better graphics

  This should eliminate the CPU-type boot loop workaround. Appreciate your help improving the Proxmox experience!

**Comment by lennyzeltser** [comment]
BTW, I just published a [QCOW2-formatted virtual appliance](https://docs.remnux.org/install-distro/get-virtual-appliance#download-virtual-appliance) of REMnux for Proxmox. If you get the chance, please give it a try.
