### ISSUE TITLE
Proxmox - not a bootable disk

### ISSUE THREAD

**Issue by kgnfth** [REMnux/docs#4]
Hello, i am getting no bootable device when i start the vm in proxmox
this is the steps i did

1. qm importovf 107 remnux-v7-focal.ova local-data
2. Set Spice Enhancements to All
3. Set Display to Spice
4. Run VM

i also tried the manual import using this site https://www.itsfullofstars.de/2019/07/import-ova-as-proxmox-vm/
but the same issue

![image](https://user-images.githubusercontent.com/73314940/127778308-09dfa480-e1cc-4cea-ad1f-b38200fc382a.png)

![image](https://user-images.githubusercontent.com/73314940/127778293-5caddab4-27e5-405f-b395-19046a3c8ad4.png)

![image](https://user-images.githubusercontent.com/73314940/127778348-1cd50626-531b-4755-be2a-f193fa1e2e64.png)

**Comment by lennyzeltser** [comment]
I haven't used Proxmox, so unfortunately I don't have any advice to offer for addressing this issue. If you figure it out, please let me know, so I can share the details with others.

The one "workaround" that comes to mind is to [install REMnux from scratch ](https://docs.remnux.org/install-distro/install-from-scratch) into your Proxmox environment, instead of attempting to import the OVA file.

**Comment by kgnfth** [comment]
@lennyzeltser i tried to install from scratch but after installing ubuntu mini.iso, and when I try to boot it gets stuck at the message "/dev/sda1 clean, **** files, ***** blocks".
